# Generated by Django 4.1.5 on 2023-01-11 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angajat', '0002_remove_angajat_varsta_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='angajat',
            name='salariu',
            field=models.IntegerField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='angajat',
            name='varsta',
            field=models.IntegerField(default=10, max_length=2),
            preserve_default=False,
        ),
    ]
